[package]
name = "reader-producer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reader = { path = "./reader" }
nats = "0.23.0"
anyhow = "1.0.62"
