[package]
name = "writer-consumer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
writer = { path = "./writer" }
nats = "0.23.0"
anyhow = "1.0.62"
